services:
  app:
    container_name: local-botnet-app
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - APP_BASE_PATH=${APP_BASE_PATH}
    volumes:
      - ../app:${APP_BASE_PATH}
    ports:
      - ${APP_PORT}:3000
    tty: true
    stdin_open: true
    restart: unless-stopped
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81" 
      - "443:443"
    volumes:
      - ../nginx/data:/data
      - ../nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge